# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
source 'https://github.com/CocoaPods/Specs.git'

target 'GIOEdemo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  #use_frameworks!

  pod 'GrowingTouch/GrowingTouchKit', '~> 1.4.0' #弹窗SDK
  pod 'GrowingTouch/GrowingPushKit', '~> 1.4.0' #推送SDK(不含图片)
  pod 'GrowingTouch/GrowingTouchBannerKit', '~> 1.4.0' #bannerSDK
  pod 'GrowingAutoTrackKit', '2.8.19'     #无埋点采集
  pod 'YYImage', '~> 1.0.4'
  pod 'YYWebImage', '~> 1.0.5'
  pod 'YYImage/WebP'
  pod 'SDCycleScrollView', '~> 1.80'

end

target 'GIOEdemoServiceExtension' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  pod 'GrowingTouch/GrowingPushExtensionKit', '~> 1.4.0' #图片推送和后台数据上报SDK

end
