# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'GIOEdemo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  #use_frameworks!

  pod 'GrowingTouch/GrowingTouchKit', '~> 1.1.0'
  pod 'GrowingTouch/GrowingPushKit', '~> 1.1.0'
  pod 'GrowingAutoTrackKit', '2.8.7'
  pod 'YYImage', '~> 1.0.4'
  pod 'YYWebImage', '~> 1.0.5'
  pod 'YYImage/WebP'
  pod 'SDCycleScrollView', '~> 1.80'

end

target 'GIOEdemoServiceExtension' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  pod 'GrowingTouch/GrowingPushExtensionKit', '~> 1.1.0'

end
